/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class App {



    public static void main(String[] args) {
        linkedList l = new linkedList();
        l.insertLast(5);
        l.insertLast(7);
        l.insertLast(8);
        l.insertBefore(8,9);
//        l.remove(5);
//        l.removeAll();
        System.out.println(l.seqSearch(9));

//        l.toString();

    }



}
