/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class App {



    public static void main(String[] args) {

        linkedList l = new linkedList();
        l.insertLast(1);
        l.insertLast(3);
        l.insertLast(6);
        l.insertLast(7);
        l.insertLast(5);
        l.reverse();
        l.toString();


















    }













    }



