/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackAndQueue;

public class App {

    public static void main(String[] args) {
//        Stack s = new Stack();
//        s.push(3);
//        s.push(4);
//        s.push(8);
//        s.push(9);
//        s.display();

        Queue q = new Queue();
        q.enqueue(3);
        q.enqueue(6);
        q.enqueue(8);
        q.dequeue();
        q.dequeue();
        System.out.println(q.peek());





    }
}
